export { default as Join } from './Join'
export { default as Instructions } from './Instructions' 
export { default as SubmitSuggestions } from './SubmitSuggestions' 
export { default as Intermission } from './Intermission' 
export { default as Scores } from './Scores' 